spring:
  application:
    name: notification-service

  profiles:
    active: elk

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#    нужен для отправки сообщений по ретраю и DLQ
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: gzip   # или lz4, или zstd, чтобы избежать работы с snappy
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

    listener:
      simple:
        prefetch: 10
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: auto          # подтверждение после успешной обработки
        default-requeue-rejected: false # poison -> DLQ
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
          multiplier: 2.0
          max-interval: 10s

app:
  topic:
    notification-events: "notification-events"
    order-create-topic: "order.outbox"
  provider:
    url: http://provider-service:8198/api/mock-provider

server:
  port: 8082

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0    # в демо берём 100%, в production меньше (0.1, 0.01)
    propagation:
      type: w3c           # W3C Trace Context, traceparent: содержит Trace ID, Span ID и флаги трассировки
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
          - loggers
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN